[build]
  command = "hugo --cleanDestinationDir --enableGitInfo --gc --logLevel info --minify --printPathWarnings --theme terminal"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.2"